---
resources:
- name: resource-boxofjam
  type: git
  source:
    uri: https://github.com/ianhomer/boxofjam.git
    branch: master

jobs:
- name: job-build
  public: true
  plan:
  - get: resource-boxofjam
  - task: build-npm
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: node}
      inputs:
        - name: resource-boxofjam
      run:
        path: ls
        args: ['-al']
        
