---
resources:
- name: resource-boxofjam
  type: git
  source:
    uri: https://github.com/ianhomer/boxofjam.git
    branch: master

jobs:
- name: job-build
  public: true
  plan:
  - get: resource-boxofjam
  - task: build-npm
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: node, tag: "8" }
      inputs:
        - name: resource-boxofjam
      caches:
        - path: resource-boxofjam/node_modules
      run:
        path: sh
        dir: resource-boxofjam
        args:
          - -exc
          - |
            node --version
            npm --version
            npm i
            npm run build

